name: kernels_vectorization

services:
  kernels_vectorization:
    image: kernels_vectorization:latest
    container_name: kernels_vectorization
    build: .
    volumes:
      - .:/app
    stdin_open: true
    tty: true